/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __accessCheck = (obj, member, msg) => {
  if (!member.has(obj))
    throw TypeError("Cannot " + msg);
};
var __privateGet = (obj, member, getter) => {
  __accessCheck(obj, member, "read from private field");
  return getter ? getter.call(obj) : member.get(obj);
};
var __privateAdd = (obj, member, value) => {
  if (member.has(obj))
    throw TypeError("Cannot add the same private member more than once");
  member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
};
var __privateSet = (obj, member, value, setter) => {
  __accessCheck(obj, member, "write to private field");
  setter ? setter.call(obj, value) : member.set(obj, value);
  return value;
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArchWikiPlugin
});
module.exports = __toCommonJS(main_exports);
var import_child_process2 = require("child_process");
var import_obsidian4 = require("obsidian");
var path2 = __toESM(require("path"));

// src/settings.ts
var import_obsidian = require("obsidian");
var ArchWikiSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("ArchWiki page directory").setDesc("Where should downloaded ArchWiki pages be stored").addText(
      (text) => text.setValue(this.plugin.settings.pageDirectory).onChange(async (value) => {
        this.plugin.settings.pageDirectory = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/suggestionModal.ts
var import_obsidian2 = require("obsidian");
var _items, _noSuggestion, _onConfirm;
var ArchWikiFuzzySuggestionModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, items, onConfirm, placeholder) {
    super(app);
    __privateAdd(this, _items, void 0);
    __privateAdd(this, _noSuggestion, void 0);
    __privateAdd(this, _onConfirm, void 0);
    __privateSet(this, _items, items);
    __privateSet(this, _onConfirm, onConfirm);
    this.setPlaceholder(placeholder);
    this.limit = 5e3;
    this.scope.register(["Ctrl"], "p", () => {
      this.inputEl.dispatchEvent(new KeyboardEvent("keydown", { key: "ArrowUp" }));
    });
    this.scope.register(["Ctrl"], "n", () => {
      this.inputEl.dispatchEvent(
        new KeyboardEvent("keydown", { key: "ArrowDown" })
      );
    });
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "to navigate" },
      { command: "ctrl p/n", purpose: "to navigate" },
      { command: "ctrl k/j", purpose: "to navigate" },
      { command: "\u21B5", purpose: "to use" },
      { command: "esc", purpose: "to dismiss" }
    ]);
  }
  getItems() {
    return __privateGet(this, _items);
  }
  getItemText(item) {
    __privateSet(this, _noSuggestion, false);
    return item;
  }
  onNoSuggestion() {
    __privateSet(this, _noSuggestion, true);
  }
  onChooseItem(item, _evt) {
    const text = __privateGet(this, _noSuggestion) ? this.inputEl.value : item;
    __privateGet(this, _onConfirm).call(this, text);
  }
};
_items = new WeakMap();
_noSuggestion = new WeakMap();
_onConfirm = new WeakMap();

// src/utils.ts
var import_child_process = require("child_process");
var import_fs = require("fs");
var import_obsidian3 = require("obsidian");
var path = __toESM(require("path"));
function isCliInstalled() {
  try {
    (0, import_child_process.execSync)("archwiki-rs -h");
    return true;
  } catch (e) {
    return false;
  }
}
function pageFileExists() {
  try {
    const info = (0, import_child_process.execSync)("archwiki-rs info -d -o", { encoding: "utf8" });
    const filePath = path.join(info.trim(), "pages.yml");
    return (0, import_fs.existsSync)(filePath);
  } catch (e) {
    return false;
  }
}
function createPageFile() {
  (0, import_child_process.exec)("archwiki-rs sync-wiki", (err) => {
    if (err) {
      const notice2 = new import_obsidian3.Notice(
        "Failed to create page file. Try running the command 'archwiki-rs sync-wiki' manually."
      );
      notice2.noticeEl.addClass("archwiki-error-notice");
      return;
    }
    const notice = new import_obsidian3.Notice("Finished fetching pages from the ArchWiki");
    notice.noticeEl.addClass("archwiki-success-notice");
  });
}
async function createIfNotExists(filename, dir, content, vault) {
  const filePath = (0, import_obsidian3.normalizePath)(path.join(dir, `${filename}.md`));
  let file;
  if (await vault.adapter.exists(filePath)) {
    file = vault.getAbstractFileByPath(filePath);
  } else {
    file = await vault.create(filePath, content);
  }
  return file;
}
async function openFileInTab(file, workspace) {
  const leaf = workspace.getLeaf("tab");
  await leaf.openFile(file);
}
function newlineStringToModalList(pages) {
  return pages.trim().split("\n").filter((s) => s.trim() !== " ");
}
function pageToSaveFilename(page) {
  return page.replace(/[^-0-9A-Za-z_]/g, "_");
}

// src/main.ts
var READ_PAGE_COMMAND = "read-page";
var DEFAULT_SETTINGS = {
  pageDirectory: "ArchWiki"
};
function openReadPageFuzzyModal(app, dir, vault, workspace) {
  let pages = [];
  try {
    const stdout = (0, import_child_process2.execSync)("archwiki-rs list-pages -f", { encoding: "utf8" });
    pages = newlineStringToModalList(stdout);
  } catch (e) {
    new import_obsidian4.Notice("Failed to get ArchWiki pages");
    return;
  }
  new ArchWikiFuzzySuggestionModal(
    app,
    pages,
    async (item) => {
      (0, import_child_process2.exec)(
        `archwiki-rs read-page -f markdown "${item}"`,
        { encoding: "utf8" },
        async (err, stdout, stderr) => {
          if (!err) {
            const page = pageToSaveFilename(item);
            const file = await createIfNotExists(
              page,
              dir,
              stdout,
              vault
            );
            openFileInTab(file, workspace);
            return;
          }
          const notice = new import_obsidian4.Notice(`Page ${item} not found`);
          notice.noticeEl.addClass("archwiki-error-notice");
          const similarPages = newlineStringToModalList(stderr);
          if (similarPages.length <= 0) {
            return;
          }
          new ArchWikiFuzzySuggestionModal(
            app,
            similarPages,
            async (item2) => {
              const page = pageToSaveFilename(item2);
              try {
                const content = (0, import_child_process2.execSync)(
                  `archwiki-rs read-page -f markdown "${page}"`,
                  { encoding: "utf8" }
                );
                const file = await createIfNotExists(
                  page,
                  dir,
                  content,
                  vault
                );
                openFileInTab(file, workspace);
              } catch (e) {
                const notice2 = new import_obsidian4.Notice(`Failed to read page ${page}`);
                notice2.noticeEl.addClass("archwiki-error-notice");
              }
            },
            "Enter similar page name..."
          ).open();
        }
      );
    },
    "Enter page name..."
  ).open();
}
var ArchWikiPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    if (!isCliInstalled()) {
      const notice = new import_obsidian4.Notice(
        `You have to install 'archwiki-rs' to use the plugin '${this.manifest.name}'`
      );
      notice.noticeEl.addClass("archwiki-warn-notice");
      return;
    }
    if (!pageFileExists()) {
      const notice = new import_obsidian4.Notice(
        "Fetching list of pages from the ArchWiki. This will take some time..."
      );
      notice.noticeEl.addClass("archwiki-info-notice");
      createPageFile();
    }
    const root = this.app.vault.getRoot().path;
    const dir = path2.join(root, this.settings.pageDirectory);
    const exists = await this.app.vault.adapter.exists(dir);
    if (!exists) {
      await this.app.vault.createFolder(dir);
    }
    this.addSettingTab(new ArchWikiSettingTab(this.app, this));
    this.addCommand({
      id: READ_PAGE_COMMAND,
      name: "Read ArchWiki page",
      callback: () => {
        openReadPageFuzzyModal(
          this.app,
          this.settings.pageDirectory,
          this.app.vault,
          this.app.workspace
        );
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};


/* nosourcemap */